### PR TITLE
fix: prevent duplicate update operations in queue (#4131)

### LINKED ISSUE #4131: [BUG] Unattended update attempts get duplicated
### Please confirm these before moving forward

- [x] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [x] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [x] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [x] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.3.5

### Windows version, edition, and architecture

Windows 11 Pro x64

### Describe your issue

If an auto-update triggers while I'm not at my PC, the next time I check it there will be a UAC prompt and a dozen or so duplicate copies of the update which I have to cancel to prevent the package from updating to the same new version a dozen times. This is particularly annoying when several updates trigger at once, because then there will be several dozen duplicates to cancel. Would it be possible to add a check to prevent the same package version from being queued multiple times so this doesn't happen? Thanks!

### Steps to reproduce the issue

_No response_

### UniGetUI Log

```text
[9/14/2025 10:33:15 AM]    __  __      _ ______     __  __  ______
                          / / / /___  (_) ____/__  / /_/ / / /  _/
                         / / / / __ \/ / / __/ _ \/ __/ / / // /
                        / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                        \____/_/ /_/_/\____/\___/\__/\____/___/
                            Welcome to UniGetUI Version 3.3.5
[9/14/2025 10:33:15 AM]
[9/14/2025 10:33:15 AM] Build 103
[9/14/2025 10:33:15 AM] Data directory C:\Users\edkol\AppData\Local\UniGetUI
[9/14/2025 10:33:15 AM] Encoding Code Page set to 437
[9/14/2025 10:33:17 AM] Loaded language locale: en
[9/14/2025 10:33:17 AM] Could not retrieve token (it may not exist): Element not found.
                        
                        Cannot get credential from Vault
[9/14/2025 10:33:18 AM] Lang files were updated successfully from GitHub
[9/14/2025 10:33:18 AM] Scoop is not enabled
[9/14/2025 10:33:18 AM] Cargo is not enabled
[9/14/2025 10:33:18 AM] vcpkg is not enabled
[9/14/2025 10:33:18 AM] PowerShell is not enabled
[9/14/2025 10:33:18 AM] Randomly-generated background API auth token: 38p7on5byxvsx5sgm2xzhtt7ku0m6y1n9vxu7rwdeip3jes5dy8wv8fdoqajj5e2
[9/14/2025 10:33:18 AM] Chocolatey is enabled and was found on C:\Users\edkol\AppData\Local\UniGetUI\Chocolatey\choco.exe
[9/14/2025 10:33:18 AM] Pip is enabled and was found on C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\python.exe
[9/14/2025 10:33:18 AM] Call to WhichMultiple with file pwsh.exe returned non-zero status 1
[9/14/2025 10:33:18 AM] Command pwsh.exe was not found on the system
[9/14/2025 10:33:18 AM] PowerShell7 is enabled but was not found on the system!
[9/14/2025 10:33:18 AM] Npm is enabled and was found on C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
[9/14/2025 10:33:18 AM] Winget is enabled and was found on C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe
[9/14/2025 10:33:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: WinGet (aka Winget)
                        █ Executable name: "winget.exe"
                        █ Executable path: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
                        █ Call arguments: ""
                        █ Version: System WinGet (CLI) Version: v1.11.430
                        █          Using Native WinGet helper (COM Api)
                        █          
                        █ WinGet is enabled and ready to go.
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/14/2025 10:33:19 AM] .NET Tool is enabled and was found on C:\Program Files\dotnet\dotnet.exe
[9/14/2025 10:33:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: .NET Tool (aka .NET Tool)
                        █ Executable name: "dotnet tool"
                        █ Executable path: "C:\Program Files\dotnet\dotnet.exe"
                        █ Call arguments: "tool "
                        █ Version: 10.0.100-rc.1.25451.107
                        █          
                        █ .NET Tool is enabled and ready to go.
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/14/2025 10:33:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Pip (aka Pip)
                        █ Executable name: "pip"
                        █ Executable path: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\python.exe"
                        █ Call arguments: "-m pip "
                        █ Version: pip 25.2 from C:\Users\edkol\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip (python 3.10)
                        █          
                        █ Pip is enabled and ready to go.
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/14/2025 10:33:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Chocolatey (aka Chocolatey)
                        █ Executable name: "choco.exe"
                        █ Executable path: "C:\Users\edkol\AppData\Local\UniGetUI\Chocolatey\choco.exe"
                        █ Call arguments: ""
                        █ Version: 2.4.2
                        █          
                        █ Chocolatey is enabled and ready to go.
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/14/2025 10:33:19 AM] UniGetUI Chocolatey was found in the path
[9/14/2025 10:33:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Npm (aka Npm)
                        █ Executable name: "npm"
                        █ Executable path: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
                        █ Call arguments: "-NoProfile -ExecutionPolicy Bypass -Command "C:\Program` Files\nodejs\npm.ps1" "
                        █ Version: 11.4.2
                        █          
                        █ Npm is enabled and ready to go.
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[9/14/2025 10:33:20 AM] Api running on http://localhost:7058
[9/14/2025 10:33:20 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[9/14/2025 10:33:20 AM] Downloaded new icons and screenshots successfully!
[9/14/2025 10:33:20 AM] Found 25 installed packages from Pip
[9/14/2025 10:33:20 AM] Found 4 installed packages from .NET Tool
[9/14/2025 10:33:20 AM] Found 4 installed packages from .NET Tool
[9/14/2025 10:33:21 AM] Manager Npm failed to list installed packages with exception JsonReaderException: 'U' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
[9/14/2025 10:33:21 AM] Since this was the first attempt, Npm.AttemptFastRepair() will be called and the procedure will be restarted
[9/14/2025 10:33:21 AM] Manager Npm failed to list available updates with exception JsonReaderException: 'U' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
[9/14/2025 10:33:21 AM] Since this was the first attempt, Npm.AttemptFastRepair() will be called and the procedure will be restarted
[9/14/2025 10:33:21 AM] Found 0 available updates from .NET Tool
[9/14/2025 10:33:21 AM] Error finding installed packages on manager Npm
[9/14/2025 10:33:21 AM] Found 2 installed packages from Chocolatey
[9/14/2025 10:33:21 AM] Error finding updates on manager Npm
[9/14/2025 10:33:21 AM] System.AggregateException: One or more errors occurred. ('U' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.)
                         ---> System.Text.Json.JsonReaderException: 'U' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
                           at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
                           at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
                           at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte)
                           at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
                           at System.Text.Json.Utf8JsonReader.Read()
                           at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1, JsonReaderOptions, MetadataDb&, StackRowStack&)
                           at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1, JsonReaderOptions, JsonTokenType )
                           at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1, JsonDocumentOptions)
                           at System.Text.Json.Nodes.JsonNode.Parse(String , Nullable`1 , JsonDocumentOptions )
                           at UniGetUI.PackageEngine.Managers.NpmManager.Npm.GetAvailableUpdates_UnSafe() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.Managers.Npm\Npm.cs:line 127
                           at System.Threading.Tasks.Task`1.InnerInvoke()
                           at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
                        --- End of stack trace from previous location ---
                           at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
                           at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
                           --- End of inner exception stack trace ---
                           at System.Threading.Tasks.Task.Wait(Int32, CancellationToken)
                           at System.Threading.Tasks.Task.Wait(TimeSpan, CancellationToken)
                           at System.Threading.Tasks.Task.Wait(TimeSpan)
                           at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager._getAvailableUpdates(Boolean SecondAttempt) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 279

(truncated to to 65536 character limit)
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet (CLI) Version: v1.11.430
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 9/14/2025 10:33:19 AM
Process end time:   9/14/2025 10:33:19 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 9/14/2025 10:33:20 AM
Process end time:   9/14/2025 10:33:23 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 10:33:20 AM
Process end time:   9/14/2025 10:33:20 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 10:33:20 AM
Process end time:   9/14/2025 10:33:22 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 10:33:20 AM
Process end time:   9/14/2025 10:33:23 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 11:33:23 AM
Process end time:   9/14/2025 11:33:26 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 11:33:26 AM
Process end time:   9/14/2025 11:33:30 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 11:33:26 AM
Process end time:   9/14/2025 11:33:28 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 12:33:30 PM
Process end time:   9/14/2025 12:33:33 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 12:33:33 PM
Process end time:   9/14/2025 12:33:36 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 12:33:33 PM
Process end time:   9/14/2025 12:33:34 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 1:33:36 PM
Process end time:   9/14/2025 1:33:44 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 1:33:44 PM
Process end time:   9/14/2025 1:33:48 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 1:33:44 PM
Process end time:   9/14/2025 1:33:46 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 2:33:48 PM
Process end time:   9/14/2025 2:33:51 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 2:33:51 PM
Process end time:   9/14/2025 2:33:56 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 2:33:51 PM
Process end time:   9/14/2025 2:33:54 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 3:33:56 PM
Process end time:   9/14/2025 3:33:58 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 3:33:58 PM
Process end time:   9/14/2025 3:34:01 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 3:33:58 PM
Process end time:   9/14/2025 3:34:00 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 4:34:01 PM
Process end time:   9/14/2025 4:34:04 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 4:34:04 PM
Process end time:   9/14/2025 4:34:08 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 4:34:04 PM
Process end time:   9/14/2025 4:34:06 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 5:34:08 PM
Process end time:   9/14/2025 5:34:09 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 5:34:09 PM
Process end time:   9/14/2025 5:34:12 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 5:34:09 PM
Process end time:   9/14/2025 5:34:10 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 6:34:12 PM
Process end time:   9/14/2025 6:34:14 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 6:34:14 PM
Process end time:   9/14/2025 6:34:18 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 6:34:14 PM
Process end time:   9/14/2025 6:34:16 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 7:34:18 PM
Process end time:   9/14/2025 7:34:20 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 7:34:20 PM
Process end time:   9/14/2025 7:34:24 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 7:34:20 PM
Process end time:   9/14/2025 7:34:22 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 8:34:25 PM
Process end time:   9/14/2025 8:34:27 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 8:34:27 PM
Process end time:   9/14/2025 8:34:30 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 8:34:27 PM
Process end time:   9/14/2025 8:34:28 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 9:34:30 PM
Process end time:   9/14/2025 9:34:32 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 9:34:32 PM
Process end time:   9/14/2025 9:34:35 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 9:34:32 PM
Process end time:   9/14/2025 9:34:34 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 9/14/2025 9:59:12 PM
Process end time:   9/14/2025 9:59:15 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 9:59:12 PM
Process end time:   9/14/2025 9:59:14 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 10:34:35 PM
Process end time:   9/14/2025 10:34:36 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 10:34:36 PM
Process end time:   9/14/2025 10:34:40 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 10:34:36 PM
Process end time:   9/14/2025 10:34:38 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/14/2025 11:34:41 PM
Process end time:   9/14/2025 11:34:43 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/14/2025 11:34:43 PM
Process end time:   9/14/2025 11:34:46 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/14/2025 11:34:43 PM
Process end time:   9/14/2025 11:34:45 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 12:34:46 AM
Process end time:   9/15/2025 12:34:49 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 12:34:49 AM
Process end time:   9/15/2025 12:34:52 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 12:34:49 AM
Process end time:   9/15/2025 12:34:50 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 1:34:52 AM
Process end time:   9/15/2025 1:34:54 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 1:34:54 AM
Process end time:   9/15/2025 1:34:58 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 1:34:54 AM
Process end time:   9/15/2025 1:34:56 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 2:34:58 AM
Process end time:   9/15/2025 2:35:00 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 2:35:00 AM
Process end time:   9/15/2025 2:35:04 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 2:35:00 AM
Process end time:   9/15/2025 2:35:02 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 3:35:05 AM
Process end time:   9/15/2025 3:35:07 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 3:35:07 AM
Process end time:   9/15/2025 3:35:11 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 3:35:07 AM
Process end time:   9/15/2025 3:35:09 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 4:35:11 AM
Process end time:   9/15/2025 4:35:13 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 4:35:13 AM
Process end time:   9/15/2025 4:35:16 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 4:35:13 AM
Process end time:   9/15/2025 4:35:14 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 5:35:16 AM
Process end time:   9/15/2025 5:35:18 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 5:35:18 AM
Process end time:   9/15/2025 5:35:21 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 5:35:18 AM
Process end time:   9/15/2025 5:35:20 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 6:35:22 AM
Process end time:   9/15/2025 6:35:24 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 6:35:24 AM
Process end time:   9/15/2025 6:35:28 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 6:35:24 AM
Process end time:   9/15/2025 6:35:26 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 7:35:28 AM
Process end time:   9/15/2025 7:35:30 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 7:35:30 AM
Process end time:   9/15/2025 7:35:34 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 7:35:30 AM
Process end time:   9/15/2025 7:35:32 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 8:35:35 AM
Process end time:   9/15/2025 8:35:37 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 8:35:37 AM
Process end time:   9/15/2025 8:35:41 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 8:35:37 AM
Process end time:   9/15/2025 8:35:40 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 9:35:41 AM
Process end time:   9/15/2025 9:35:45 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 9:35:45 AM
Process end time:   9/15/2025 9:35:48 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 9:35:45 AM
Process end time:   9/15/2025 9:35:46 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 10:35:48 AM
Process end time:   9/15/2025 10:35:51 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 10:35:51 AM
Process end time:   9/15/2025 10:35:54 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 10:35:51 AM
Process end time:   9/15/2025 10:35:52 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 11:35:54 AM
Process end time:   9/15/2025 11:35:57 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 11:35:57 AM
Process end time:   9/15/2025 11:36:00 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 11:35:57 AM
Process end time:   9/15/2025 11:35:59 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 12:36:00 PM
Process end time:   9/15/2025 12:36:03 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 12:36:03 PM
Process end time:   9/15/2025 12:36:06 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 12:36:03 PM
Process end time:   9/15/2025 12:36:04 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 1:36:06 PM
Process end time:   9/15/2025 1:36:08 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 1:36:08 PM
Process end time:   9/15/2025 1:36:12 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 1:36:08 PM
Process end time:   9/15/2025 1:36:10 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 2:36:12 PM
Process end time:   9/15/2025 2:36:15 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 2:36:15 PM
Process end time:   9/15/2025 2:36:18 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 2:36:15 PM
Process end time:   9/15/2025 2:36:16 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 3:36:18 PM
Process end time:   9/15/2025 3:36:20 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 3:36:20 PM
Process end time:   9/15/2025 3:36:25 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 3:36:20 PM
Process end time:   9/15/2025 3:36:22 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 4:36:25 PM
Process end time:   9/15/2025 4:36:27 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 4:36:27 PM
Process end time:   9/15/2025 4:36:30 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 4:36:27 PM
Process end time:   9/15/2025 4:36:28 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 5:36:30 PM
Process end time:   9/15/2025 5:36:33 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 5:36:33 PM
Process end time:   9/15/2025 5:36:38 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 5:36:33 PM
Process end time:   9/15/2025 5:36:34 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 6:36:38 PM
Process end time:   9/15/2025 6:36:41 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 6:36:41 PM
Process end time:   9/15/2025 6:36:44 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 6:36:41 PM
Process end time:   9/15/2025 6:36:42 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 7:36:44 PM
Process end time:   9/15/2025 7:36:46 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 7:36:46 PM
Process end time:   9/15/2025 7:36:51 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 7:36:46 PM
Process end time:   9/15/2025 7:36:48 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 8:36:51 PM
Process end time:   9/15/2025 8:36:53 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 8:36:53 PM
Process end time:   9/15/2025 8:36:56 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 8:36:53 PM
Process end time:   9/15/2025 8:36:55 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 9:36:56 PM
Process end time:   9/15/2025 9:36:59 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 9:36:59 PM
Process end time:   9/15/2025 9:37:02 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 9:36:59 PM
Process end time:   9/15/2025 9:37:00 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 10:37:02 PM
Process end time:   9/15/2025 10:37:03 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 10:37:03 PM
Process end time:   9/15/2025 10:37:06 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 10:37:03 PM
Process end time:   9/15/2025 10:37:05 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/15/2025 11:37:06 PM
Process end time:   9/15/2025 11:37:07 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/15/2025 11:37:07 PM
Process end time:   9/15/2025 11:37:11 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/15/2025 11:37:07 PM
Process end time:   9/15/2025 11:37:09 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 12:37:11 AM
Process end time:   9/16/2025 12:37:14 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 12:37:14 AM
Process end time:   9/16/2025 12:37:17 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 12:37:14 AM
Process end time:   9/16/2025 12:37:15 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 1:37:18 AM
Process end time:   9/16/2025 1:37:20 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 1:37:20 AM
Process end time:   9/16/2025 1:37:24 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 1:37:20 AM
Process end time:   9/16/2025 1:37:22 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 2:37:24 AM
Process end time:   9/16/2025 2:37:26 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 2:37:26 AM
Process end time:   9/16/2025 2:37:29 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 2:37:26 AM
Process end time:   9/16/2025 2:37:27 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 3:37:29 AM
Process end time:   9/16/2025 3:37:31 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 3:37:31 AM
Process end time:   9/16/2025 3:37:36 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 3:37:31 AM
Process end time:   9/16/2025 3:37:33 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 4:37:36 AM
Process end time:   9/16/2025 4:37:38 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 4:37:38 AM
Process end time:   9/16/2025 4:37:41 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 4:37:38 AM
Process end time:   9/16/2025 4:37:39 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 5:37:41 AM
Process end time:   9/16/2025 5:37:43 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 5:37:43 AM
Process end time:   9/16/2025 5:37:46 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 5:37:43 AM
Process end time:   9/16/2025 5:37:45 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 6:37:46 AM
Process end time:   9/16/2025 6:37:48 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 6:37:48 AM
Process end time:   9/16/2025 6:37:52 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 6:37:48 AM
Process end time:   9/16/2025 6:37:50 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 7:37:52 AM
Process end time:   9/16/2025 7:37:54 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 7:37:54 AM
Process end time:   9/16/2025 7:37:58 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 7:37:54 AM
Process end time:   9/16/2025 7:37:56 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 9/16/2025 8:26:19 AM
Process end time:   9/16/2025 8:26:24 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 8:26:19 AM
Process end time:   9/16/2025 8:26:22 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 8:37:59 AM
Process end time:   9/16/2025 8:37:59 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 8:37:59 AM
Process end time:   9/16/2025 8:38:03 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 8:37:59 AM
Process end time:   9/16/2025 8:38:01 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 9:38:03 AM
Process end time:   9/16/2025 9:38:05 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 9:38:05 AM
Process end time:   9/16/2025 9:38:08 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 9:38:05 AM
Process end time:   9/16/2025 9:38:07 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 10:38:09 AM
Process end time:   9/16/2025 10:38:09 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 10:38:09 AM
Process end time:   9/16/2025 10:38:12 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 10:38:09 AM
Process end time:   9/16/2025 10:38:11 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 11:38:12 AM
Process end time:   9/16/2025 11:38:15 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 11:38:15 AM
Process end time:   9/16/2025 11:38:19 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 11:38:15 AM
Process end time:   9/16/2025 11:38:17 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 12:38:19 PM
Process end time:   9/16/2025 12:38:22 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 12:38:22 PM
Process end time:   9/16/2025 12:38:25 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 12:38:22 PM
Process end time:   9/16/2025 12:38:23 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 1:38:25 PM
Process end time:   9/16/2025 1:38:26 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 1:38:26 PM
Process end time:   9/16/2025 1:38:29 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 1:38:26 PM
Process end time:   9/16/2025 1:38:27 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 2:38:29 PM
Process end time:   9/16/2025 2:38:32 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 2:38:32 PM
Process end time:   9/16/2025 2:38:36 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 2:38:32 PM
Process end time:   9/16/2025 2:38:34 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 3:38:36 PM
Process end time:   9/16/2025 3:38:38 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 3:38:38 PM
Process end time:   9/16/2025 3:38:41 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 3:38:38 PM
Process end time:   9/16/2025 3:38:40 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 4:38:41 PM
Process end time:   9/16/2025 4:38:44 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 4:38:44 PM
Process end time:   9/16/2025 4:38:47 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 4:38:44 PM
Process end time:   9/16/2025 4:38:46 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 5:38:47 PM
Process end time:   9/16/2025 5:38:50 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 5:38:50 PM
Process end time:   9/16/2025 5:38:53 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 5:38:50 PM
Process end time:   9/16/2025 5:38:52 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 6:38:54 PM
Process end time:   9/16/2025 6:38:54 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 6:38:54 PM
Process end time:   9/16/2025 6:38:57 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 9/16/2025 6:38:54 PM
Process end time:   9/16/2025 6:38:56 PM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\edkol\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity "
Process start time: 9/16/2025 7:38:58 PM
Process end time:   9/16/2025 7:38:58 PM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 9/16/2025 7:38:58 PM
Process end time:   9/16/2025 7:39:02 PM


(truncated to to 65536 character limit)
```

### Relevant information

_No response_

### Screenshots and videos

_No response_

### PR DESCRIPTION
**Pull request by GioAbq**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#coding), and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**.
- [x] **Have you checked that there aren't other open [pull requests](https://github.com/marticliment/WingetUI/pulls) for the same changes?**
- [x] **Have you tested that the committed code can be executed without errors?**
- [x] **This PR is not composed of garbage changes used to farm GitHub activity to enter potential Crypto AirDrops.**
Any user suspected of farming GitHub activity with crypto purposes will get banned. Submitting broken code wastes the contributors' time, who have to spend their free time reviewing, fixing, and testing code that does not even compile breaks other features, or does not introduce any useful changes. I appreciate your understanding.
-----

## Description

This PR adds duplicate detection logic to prevent the same package update operation from being queued multiple times during unattended updates.

### Problem
When unattended auto-updates trigger while the user is away from their PC (particularly when UAC prompts are waiting for user interaction), the `UpdateAll()` method runs repeatedly and creates dozens of duplicate operations for the same package. This happens because:

1. Auto-updates call `UpdateAll()` periodically (every 60 minutes on success, 10 minutes on failure)
2. When UAC prompts are waiting, operations are created but package tags aren't set immediately
3. The next `UpdateAll()` call doesn't detect the existing operation and creates duplicates
4. Users return to find dozens of duplicate operations and UAC prompts to cancel

### Solution
Added duplicate detection in the `Update()` method (`src/UniGetUI/AppOperationHelper.cs`) that:

- Checks the operation list before creating a new `UpdatePackageOperation`
- Uses `GetHash()` to compare packages by Manager, Source, and Package ID
- Only checks operations with status `InQueue` or `Running`
- Returns the existing operation if a duplicate is detected, preventing queue pollution
- Logs an informational message when duplicates are skipped

### Changes
- **Modified:** `src/UniGetUI/AppOperationHelper.cs` - Added 14 lines of duplicate detection logic

### Testing
- ✅ Code compiles without errors
- ✅ No linter errors introduced
- ✅ Uses existing infrastructure (operation list and package hash comparison)
- ✅ Minimal, focused change with clear logging

### Expected Impact
After this fix:
- Users will see only **one** update operation per package
- Only **one** UAC prompt per package update
- No more dozens of duplicate operations to cancel
- Cleaner operation queue even when away during auto-updates

-----
Closes #4131

### CODE REVIEW

File: src/UniGetUI/AppOperationHelper.cs [hunk 1]
```diff
@@ -239,6 +239,20 @@ public static void Install(IReadOnlyList<IPackage> packages, TEL_InstallReferral
                 return null;
             }
 
+            // Check for duplicate operations already in the queue
```
Comment (marticliment) [inline src/UniGetUI/AppOperationHelper.cs]: This code will not allow a package to be set to be updated twice, even manually. 
Please move this check from here to the `UpdateAll()` and `UpdateAllForManager(...)` methods.

**Comment by GioAbq** [comment]
Thanks for the feedback! You're absolutely right - I've moved the duplicate detection logic to only apply during automatic updates.
I've also added tests in UniGetUI.PackageEngine.Serializable.Tests that verify Package.GetHash() works correctly for duplicate detection
The duplicate detection now only triggers during unattended update scenarios (like the issue #4131 describes), while manual user actions remain unrestricted.
